<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('jobeet_category', 'description', 'string', '255', array(
             'notnull' => '1',
             'unique' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('jobeet_category', 'description');
    }
}